version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

